### ISSUE TITLE
Running the retrain.py script resulted in an error

### ISSUE THREAD

**Issue by ericsavoiewaltz** [testdotai/classifier-builder#1]
Running 
`classifier-builder ericsavoie$ python retrain.py --image_dir training_images/ --output_graph output/saved_model.pb --output_labels output/saved_model.pbtxt --how_many_training_steps 4000 --learning_rate 0.30 --testing_percentage 25 --validation_percentage 25 --eval_step_interval 50 --train_batch_size 2000 --test_batch_size -1 --validation_batch_size -1 --bottleneck_dir /tmp/bottleneck
`

At the very end it produced an error:

`INFO:tensorflow:Saver not created because there are no variables in the graph to restore
INFO:tensorflow:Restoring parameters from /tmp/_retrain_checkpoint
INFO:tensorflow:Final test accuracy = 67.0% (N=38201)
INFO:tensorflow:Save final result to : output/saved_model.pb
2018-11-05 13:19:31.581472: W tensorflow/core/graph/graph_constructor.cc:1263] Importing a graph with a lower producer version 26 into an existing graph with producer version 27. Shape inference will have run different parts of the graph with different producer versions.
INFO:tensorflow:Saver not created because there are no variables in the graph to restore
INFO:tensorflow:Restoring parameters from /tmp/_retrain_checkpoint
INFO:tensorflow:Froze 137 variables.
INFO:tensorflow:Converted 137 variables to const ops.
Traceback (most recent call last):
  File "retrain.py", line 1333, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "retrain.py", line 1151, in main
    save_graph_to_file(graph, FLAGS.output_graph, module_spec, class_count)
  File "retrain.py", line 909, in save_graph_to_file
    f.write(output_graph_def.SerializeToString())
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tensorflow/python/lib/io/file_io.py", line 108, in write
    self._prewrite_check()
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tensorflow/python/lib/io/file_io.py", line 94, in _prewrite_check
    compat.as_bytes(self.__name), compat.as_bytes(self.__mode), status)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tensorflow/python/framework/errors_impl.py", line 526, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: output/saved_model.pb; No such file or directory`

**Comment by mar0ra** [comment]
Got past this error by manually creating a folder 'output' under 'classifier-builder', the script seems to be making an assumption that the folder exists. 
Probably need to add something like this:
`ensure_dir_exists(output_dir)`

**Comment by ericsavoiewaltz** [comment]
Damn I feel stupid. I thought it was for sure too simple of a fix and that I hadn't given Python the right permissions somehow. But I did add the output folder before leaving last night I should've ran the script as well. 

Giving it a shot now.

**Comment by mar0ra** [comment]
haha I almost didnot try it... takes a long time to run. I will look at the script tonite, we might be able to improve it by passing in --output_dir and removing --output_graph --output_labels.

**Comment by cnavrides** [comment]
Closing this out. Will add in a check for the folder
