### ISSUE TITLE
Failed to build on macOS 10.14.5 when Final test accuracy = 67.2%

### ISSUE THREAD

**Issue by yangquan1982** [testdotai/classifier-builder#5]
```
INFO:tensorflow:2019-05-27 12:54:22.651062: Step 3999: Train accuracy = 77.1%
I0527 12:54:22.651128 4364408256 retrain.py:1099] 2019-05-27 12:54:22.651062: Step 3999: Train accuracy = 77.1%
INFO:tensorflow:2019-05-27 12:54:22.651270: Step 3999: Cross entropy = 1.030875
I0527 12:54:22.651283 4364408256 retrain.py:1101] 2019-05-27 12:54:22.651270: Step 3999: Cross entropy = 1.030875
INFO:tensorflow:2019-05-27 12:54:51.107501: Step 3999: Validation accuracy = 66.9% (N=38485)
I0527 12:54:51.107573 4364408256 retrain.py:1120] 2019-05-27 12:54:51.107501: Step 3999: Validation accuracy = 66.9% (N=38485)
2019-05-27 12:55:26.988836: W tensorflow/core/graph/graph_constructor.cc:1272] Importing a graph with a lower producer version 26 into an existing graph with producer version 27. Shape inference will have run different parts of the graph with different producer versions.
INFO:tensorflow:Saver not created because there are no variables in the graph to restore
I0527 12:55:29.890471 4364408256 saver.py:1483] Saver not created because there are no variables in the graph to restore
WARNING:tensorflow:From /usr/local/lib/python3.6/site-packages/tensorflow/python/training/saver.py:1266: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
W0527 12:55:30.225637 4364408256 deprecation.py:323] From /usr/local/lib/python3.6/site-packages/tensorflow/python/training/saver.py:1266: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
INFO:tensorflow:Restoring parameters from /tmp/_retrain_checkpoint
I0527 12:55:30.231771 4364408256 saver.py:1270] Restoring parameters from /tmp/_retrain_checkpoint
INFO:tensorflow:Final test accuracy = 67.2% (N=38201)
I0527 12:55:31.543164 4364408256 retrain.py:856] Final test accuracy = 67.2% (N=38201)
INFO:tensorflow:Save final result to : output/saved_model.pb
I0527 12:55:31.774097 4364408256 retrain.py:1148] Save final result to : output/saved_model.pb
2019-05-27 12:55:31.840187: W tensorflow/core/graph/graph_constructor.cc:1272] Importing a graph with a lower producer version 26 into an existing graph with producer version 27. Shape inference will have run different parts of the graph with different producer versions.
INFO:tensorflow:Saver not created because there are no variables in the graph to restore
I0527 12:55:33.283593 4364408256 saver.py:1483] Saver not created because there are no variables in the graph to restore
INFO:tensorflow:Restoring parameters from /tmp/_retrain_checkpoint
I0527 12:55:33.602644 4364408256 saver.py:1270] Restoring parameters from /tmp/_retrain_checkpoint
WARNING:tensorflow:From retrain.py:906: convert_variables_to_constants (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.compat.v1.graph_util.convert_variables_to_constants
W0527 12:55:33.850260 4364408256 deprecation.py:323] From retrain.py:906: convert_variables_to_constants (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.compat.v1.graph_util.convert_variables_to_constants
WARNING:tensorflow:From /usr/local/lib/python3.6/site-packages/tensorflow/python/framework/graph_util_impl.py:245: extract_sub_graph (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.compat.v1.graph_util.extract_sub_graph
W0527 12:55:33.850518 4364408256 deprecation.py:323] From /usr/local/lib/python3.6/site-packages/tensorflow/python/framework/graph_util_impl.py:245: extract_sub_graph (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.compat.v1.graph_util.extract_sub_graph
INFO:tensorflow:Froze 137 variables.
I0527 12:55:34.327029 4364408256 graph_util_impl.py:268] Froze 137 variables.
INFO:tensorflow:Converted 137 variables to const ops.
I0527 12:55:34.352867 4364408256 graph_util_impl.py:301] Converted 137 variables to const ops.
Traceback (most recent call last):
  File "retrain.py", line 1333, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "retrain.py", line 1151, in main
    save_graph_to_file(graph, FLAGS.output_graph, module_spec, class_count)
  File "retrain.py", line 909, in save_graph_to_file
    f.write(output_graph_def.SerializeToString())
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/lib/io/file_io.py", line 108, in write
    self._prewrite_check()
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/lib/io/file_io.py", line 94, in _prewrite_check
    compat.as_bytes(self.__name), compat.as_bytes(self.__mode), status)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: output/saved_model.pb; No such file or directory
```

**Comment by cuihl2013** [comment]
我遇到同样的问题了，请问你的问题解决了吗

**Comment by dutradev** [comment]
@cuihl2013  you must create folder output in repo root.
![Screenshot from 2020-02-19 10-48-52](https://user-images.githubusercontent.com/22908283/74800392-dc0cf500-5305-11ea-9256-fa6e1c1f66ce.png)
